# Copyright The OpenTelemetry Authors
# SPDX-License-Identifier: Apache-2.0

name: build-and-test
run-name: ${{ github.actor }} is running  GitHub Actions
on:
  push:
    branches:
      - main
  pull_request:
    paths:

env:
  BENV_IMAGE: ${{ vars.DOCKER_HUB_URL }}/benv-final

concurrency:
  group: build-and-test-${{ github.event.pull_request_number || github.ref }}
  cancel-in-progress: true

jobs:
  clang-format-check:
    runs-on: ubuntu-20.04
    name: clang-format-check

    steps:
    - name: Print github workspace
      run: |
        echo "github.workspace = ${{ github.workspace }}"
        echo "pr.ref = ${{github.event.pull_request.head.ref}}"
        echo "github.ref = ${{ github.ref }}"
        echo "$GITHUB_CONTEXT"

    - name: Check out the codebase
      uses: actions/checkout@v3

    - name: Get current date
      id: date
      run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT  

    - name: Runs format checker
      run: |
        sudo apt update
        sudo apt install -y clang-format-11
        cd ${{ github.workspace }}
        ./.github/workflows/scripts/check-clang-format.sh

    outputs:
      date: ${{ steps.date.outputs.date }}        

  build-and-push-reducer-docker-image:
    name: build-and-push-reducer-docker-image
    runs-on: ubuntu-20.04
    needs: [clang-format-check]
    steps:
    - name: Check out the codebase
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: build-and-push-reducer-docker-image
      env:
        PASS: ${{ secrets.DOCKER_HUB_PASSWORD }}
      run: |
        echo $BENV_IMAGE
        echo "github.workspace = ${{ github.workspace }}"
        docker pull $BENV_IMAGE
        git submodule update  --init --recursive
        docker run -t \
        --rm \
        --mount "type=bind,source=/var/run/docker.sock,destination=/var/run/docker.sock" \
        --mount "type=bind,source=$(git rev-parse --show-toplevel),destination=/root/src,readonly" \
        --env EBPF_NET_SRC=/root/src \
        --env EBPF_NET_OUT_DIR=/root/out \
        --workdir=/root/out \
        $BENV_IMAGE \
        ../build.sh reducer-docker
        docker login ${{ vars.DOCKER_HUB }} -u ${{ secrets.DOCKER_HUB_USERNAME }} -p "$PASS"
        reducer_image=${{ vars.DOCKER_HUB_URL }}/reducer:${{ needs.clang-format-check.outputs.date }}-${{github.event.pull_request.head.ref}}-${GITHUB_SHA:0:7}
        echo $reducer_image
        docker tag reducer:latest $reducer_image
        docker push $reducer_image

  build-and-push-kernel-collector-docker-image:
    name: build-and-push-kernel-collector-docker-image
    runs-on: ubuntu-20.04
    needs: [clang-format-check]
    steps:
    - name: Check out the codebase
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: build-and-push-kernel-collector-docker-image
      env:
        PASS: ${{ secrets.DOCKER_HUB_PASSWORD }}
      run: |
        echo "github.workspace = ${{ github.workspace }}"
        docker pull $BENV_IMAGE
        git submodule update  --init --recursive
        docker run -t \
        --rm \
        --mount "type=bind,source=/var/run/docker.sock,destination=/var/run/docker.sock" \
        --mount "type=bind,source=$(git rev-parse --show-toplevel),destination=/root/src,readonly" \
        --env EBPF_NET_SRC=/root/src \
        --env EBPF_NET_OUT_DIR=/root/out \
        --workdir=/root/out \
        $BENV_IMAGE \
        ../build.sh kernel-collector-docker
        docker login ${{ vars.DOCKER_HUB }} -u ${{ secrets.DOCKER_HUB_USERNAME }} -p "$PASS"
        kernel_collector_image=${{ vars.DOCKER_HUB_URL }}/kernel-collector:${{ needs.clang-format-check.outputs.date }}-${{github.event.pull_request.head.ref}}-${GITHUB_SHA:0:7}
        echo $kernel_collector_image
        docker tag kernel-collector:latest $kernel_collector_image
        docker push $kernel_collector_image


  build-k8s-relay:
    name: build-k8s-relay
    runs-on: ubuntu-20.04
    needs: [clang-format-check]
    steps:
    - name: Check out the codebase
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: build k8s-relay
      run: |
        echo "github.workspace = ${{ github.workspace }}"
        docker pull $BENV_IMAGE
        git submodule update  --init --recursive
        docker run -t \
        --rm \
        --mount "type=bind,source=/var/run/docker.sock,destination=/var/run/docker.sock" \
        --mount "type=bind,source=$(git rev-parse --show-toplevel),destination=/root/src,readonly" \
        --env EBPF_NET_SRC=/root/src \
        --env EBPF_NET_OUT_DIR=/root/out \
        --workdir=/root/out \
        $BENV_IMAGE \
        ../build.sh k8s-relay

  build-cloud-collector:
    name: build-cloud-collector
    runs-on: ubuntu-20.04
    needs: [clang-format-check]
    steps:
    - name: Check out the codebase
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: build cloud-collector
      run: |
        echo "github.workspace = ${{ github.workspace }}"
        docker pull $BENV_IMAGE
        git submodule update  --init --recursive
        docker run -t \
        --rm \
        --mount "type=bind,source=/var/run/docker.sock,destination=/var/run/docker.sock" \
        --mount "type=bind,source=$(git rev-parse --show-toplevel),destination=/root/src,readonly" \
        --env EBPF_NET_SRC=/root/src \
        --env EBPF_NET_OUT_DIR=/root/out \
        --workdir=/root/out \
        $BENV_IMAGE \
        ../build.sh cloud-collector

  build-k8s-watcher:
    name: build-k8s-watcher
    runs-on: ubuntu-20.04
    needs: [clang-format-check]
    steps:
    - name: Check out the codebase
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: build k8s-watcher
      run: |
        echo "github.workspace = ${{ github.workspace }}"
        docker pull $BENV_IMAGE
        git submodule update  --init --recursive
        docker run -t \
        --rm \
        --mount "type=bind,source=/var/run/docker.sock,destination=/var/run/docker.sock" \
        --mount "type=bind,source=$(git rev-parse --show-toplevel),destination=/root/src,readonly" \
        --env EBPF_NET_SRC=/root/src \
        --env EBPF_NET_OUT_DIR=/root/out \
        --workdir=/root/out \
        $BENV_IMAGE \
        ../build.sh k8s-watcher

  build-run-unit-tests:
    name: build-run-unit-tests
    runs-on: ubuntu-20.04
    needs: [clang-format-check]
    steps:
    - name: Check out the codebase
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: run unit tests
      run: |
        echo "github.workspace = ${{ github.workspace }}"
        docker pull $BENV_IMAGE
        git submodule update  --init --recursive
        docker run -t \
        --rm \
        --mount "type=bind,source=/var/run/docker.sock,destination=/var/run/docker.sock" \
        --mount "type=bind,source=$(git rev-parse --show-toplevel),destination=/root/src,readonly" \
        --env EBPF_NET_SRC=/root/src \
        --env EBPF_NET_OUT_DIR=/root/out-test \
        --workdir=/root/out-test \
        $BENV_IMAGE \
        ../build.sh unit_tests test

  build-run-unit-tests-with-asan-and-debug-flags:
    name: build-run-unit-tests-with-asan-and-debug-flags
    runs-on: ubuntu-20.04
    needs: [clang-format-check]
    steps:
    - name: Check out the codebase
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: build unit tests with asan and debug flags on then run all tests
      run: |
        docker pull $BENV_IMAGE
        git submodule update  --init --recursive
        docker run -t \
        --rm \
        --mount "type=bind,source=/var/run/docker.sock,destination=/var/run/docker.sock" \
        --mount "type=bind,source=$(git rev-parse --show-toplevel),destination=/root/src,readonly" \
        --env EBPF_NET_SRC=/root/src \
        --env EBPF_NET_OUT_DIR=/root/out-test \
        --workdir=/root/out-test \
        $BENV_IMAGE \
        ../build.sh --debug --asan unit_tests test

  run-kernel-header-tests:
    name: run-kernel-header-tests
    needs: [build-and-push-reducer-docker-image, build-and-push-kernel-collector-docker-image]
    runs-on: macos-12
    env:
      EBPF_NET_SRC_ROOT: ${{ github.workspace }}
      DOCKER_HUB_PATH: ${{ vars.DOCKER_HUB_URL }}
    steps:
    - name: Check out the codebase
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - uses: dorny/paths-filter@v2
      id: changes
      with:
        filters: |
          kernel:
            - 'collector/kernel/**'
          github:
            - '.github/**'

    - name: Get current date
      id: date
      run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

    - name: Run kernel headers test for multiple linux distributions
      id: run-kernel-header-tests
      if: steps.changes.outputs.kernel == 'true' || steps.changes.outputs.github == 'true'
      run: |
        ./test/kernel-headers/run-tests.sh ${{ needs.clang-format-check.outputs.date }}-${{github.event.pull_request.head.ref}}-${GITHUB_SHA:0:7}
